// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmptfnpgxlbvovuivyns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptcHRmbnBneGxidm92dWl2eW5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDg2NDMsImV4cCI6MjA2NjUyNDY0M30.BXW8z9DYjzSu4tpwRlwjchvxkyDD1j9VZHczYq7ENP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);